my-gotty:
  hostname: mygotty
  ports:
  - 8989:8080
  tty: true
  image: modenaf360/gotty:latest
  stdin_open: true
  tty: true                     #using bash TTY mode (pseudo-TTY)
  securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN","NET_RAW"]
